---
title: "Diversity"
author: "Shozen Dan"
date: "10/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(haven)
```

```{r import datasets}
income.2011 <- read_dta("../../data/Household_Income_2011.dta")
income.2013 <- read_dta("../../data/Household_Income_2013.dta")
income.2015 <- read_dta("../../data/Household_Income_2015.dta")
income.2018 <- read_dta("../../data/Household_Income_2018.dta")
psu <- read_dta("../../data/PSU.dta")
```

```{r, message=FALSE}
# 2011
div.2011 <- income.2011 %>% 
  select(communityID, ge004, ge006, ge007, starts_with("ge009")) %>% 
  mutate(
    ge004 = ifelse(ge004 == 0, 1, ge004),
    ge006 = replace_na(ge006, 0),
    ge007 = replace_na(ge007, 0),
    food_expence = 4*(ge006 + ge007)/ge004,
    ge009_1 = case_when(ge009_1 < 0 ~ 0, TRUE ~ ge009_1),
    ge009_2 = case_when(ge009_2 < 0 ~ 0, TRUE ~ ge009_2),
    ge009_3 = case_when(ge009_3 < 0 ~ 0, TRUE ~ ge009_3),
    ge009_4 = case_when(ge009_4 < 0 ~ 0, TRUE ~ ge009_4),
    ge009_5 = case_when(ge009_5 < 0 ~ 0, TRUE ~ ge009_5),
    ge009_6 = case_when(ge009_6 < 0 ~ 0, TRUE ~ ge009_6),
    ge009_7 = case_when(ge009_7 < 0 ~ 0, TRUE ~ ge009_7)
  ) %>%
  filter(food_expence != Inf) %>% 
  mutate(
    monthly_PCE = food_expence + ge009_1 + ge009_2 + ge009_3 + ge009_4 + ge009_5 + ge009_6 + ge009_7,
  ) %>% 
  group_by(communityID) %>% 
  summarise(
    sd_monthly_PCE = sd(monthly_PCE, na.rm=T)
  ) %>%
  select(communityID, sd_monthly_PCE)

# 2013
div.2013 <- income.2013 %>% 
  select(communityID, ge004, ge006, ge007, starts_with("ge009")) %>% 
  mutate(
    ge004 = ifelse(ge004 == 0, 1, ge004),
    ge006 = replace_na(ge006, 0),
    ge007 = replace_na(ge007, 0),
    food_expence = 4*(ge006 + ge007)/ge004,
    ge009_1 = case_when(ge009_1 < 0 ~ 0, TRUE ~ ge009_1),
    ge009_2 = case_when(ge009_2 < 0 ~ 0, TRUE ~ ge009_2),
    ge009_3 = case_when(ge009_3 < 0 ~ 0, TRUE ~ ge009_3),
    ge009_4 = case_when(ge009_4 < 0 ~ 0, TRUE ~ ge009_4),
    ge009_5 = case_when(ge009_5 < 0 ~ 0, TRUE ~ ge009_5),
    ge009_6 = case_when(ge009_6 < 0 ~ 0, TRUE ~ ge009_6),
    ge009_7 = case_when(ge009_7 < 0 ~ 0, TRUE ~ ge009_7)
  ) %>%
  filter(food_expence != Inf) %>% 
  mutate(
    monthly_PCE = food_expence + ge009_1 + ge009_2 + ge009_3 + ge009_4 + ge009_5 + ge009_6 + ge009_7,
  ) %>% 
  group_by(communityID) %>% 
  summarise(
    sd_monthly_PCE = sd(monthly_PCE, na.rm=T)
  ) %>%
  select(communityID, sd_monthly_PCE)

# 2015
div.2015 <- income.2015 %>% 
  select(communityID, ge004, ge006, ge007, starts_with("ge009")) %>% 
  mutate(
    ge004 = ifelse(ge004 == 0, 1, ge004),
    ge006 = replace_na(ge006, 0),
    ge007 = replace_na(ge007, 0),
    food_expence = 4*(ge006 + ge007)/ge004,
    ge009_1 = case_when(ge009_1 < 0 ~ 0, TRUE ~ ge009_1),
    ge009_2 = case_when(ge009_2 < 0 ~ 0, TRUE ~ ge009_2),
    ge009_3 = case_when(ge009_3 < 0 ~ 0, TRUE ~ ge009_3),
    ge009_4 = case_when(ge009_4 < 0 ~ 0, TRUE ~ ge009_4),
    ge009_5 = case_when(ge009_5 < 0 ~ 0, TRUE ~ ge009_5),
    ge009_6 = case_when(ge009_6 < 0 ~ 0, TRUE ~ ge009_6),
    ge009_7 = case_when(ge009_7 < 0 ~ 0, TRUE ~ ge009_7)
  ) %>%
  filter(food_expence != Inf) %>% 
  mutate(
    monthly_PCE = food_expence + ge009_1 + ge009_2 + ge009_3 + ge009_4 + ge009_5 + ge009_6 + ge009_7,
  ) %>% 
  group_by(communityID) %>% 
  summarise(
    sd_monthly_PCE = sd(monthly_PCE, na.rm=T)
  ) %>%
  select(communityID, sd_monthly_PCE)

# 2018
div.2018 <- income.2018 %>% 
  select(communityID, ge004, ge006_w4, ge007_w4, starts_with("ge009")) %>% 
  mutate(
    ge004 = ifelse(ge004 == 0, 1, ge004),
    ge006 = replace_na(ge006_w4, 0),
    ge007 = replace_na(ge007_w4, 0),
    food_expence = 4*(ge006_w4 + ge007_w4)/ge004,
    ge009_1 = case_when(ge009_1 < 0 ~ 0, TRUE ~ ge009_1),
    ge009_2 = case_when(ge009_2 < 0 ~ 0, TRUE ~ ge009_2),
    ge009_3 = case_when(ge009_3 < 0 ~ 0, TRUE ~ ge009_3),
    ge009_4 = case_when(ge009_4 < 0 ~ 0, TRUE ~ ge009_4),
    ge009_5 = case_when(ge009_5 < 0 ~ 0, TRUE ~ ge009_5),
    ge009_6 = case_when(ge009_6 < 0 ~ 0, TRUE ~ ge009_6),
    ge009_7 = case_when(ge009_7 < 0 ~ 0, TRUE ~ ge009_7)
  ) %>%
  filter(food_expence != Inf) %>% 
  mutate(
    monthly_PCE = food_expence + ge009_1 + ge009_2 + ge009_3 + ge009_4 + ge009_5 + ge009_6 + ge009_7,
  ) %>% 
  group_by(communityID) %>% 
  summarise(
    sd_monthly_PCE = sd(monthly_PCE, na.rm=T)
  ) %>%
  select(communityID, sd_monthly_PCE)
```

```{r}
urban.score.div <- rbind(
  mutate(div.2011, year="2011"),
  mutate(div.2013, year="2013"),
  mutate(div.2015, year="2015"),
  mutate(div.2018, year="2018")
)

median.score <- median(urban.score.div$sd_monthly_PCE, na.rm=T)
min.score <- min(urban.score.div$sd_monthly_PCE, na.rm=T)
max.score <- max(urban.score.div$sd_monthly_PCE, na.rm=T)

cutoff.lower <- round(seq(from=min.score, to=median.score, length.out = 11), 2)
cutoff.higher <- round(seq(from=median.score, to=max.score, length.out = 10), 2)

urban.score.div <- urban.score.div %>% 
  mutate(
    urban_score_div = case_when(
      sd_monthly_PCE < cutoff.lower[1] ~ 0,
      sd_monthly_PCE < cutoff.lower[2] ~ 0.5,
      sd_monthly_PCE < cutoff.lower[3] ~ 1,
      sd_monthly_PCE < cutoff.lower[4] ~ 1.5,
      sd_monthly_PCE < cutoff.lower[5] ~ 2,
      sd_monthly_PCE < cutoff.lower[6] ~ 2.5,
      sd_monthly_PCE < cutoff.lower[7] ~ 3,
      sd_monthly_PCE < cutoff.lower[8] ~ 3.5,
      sd_monthly_PCE < cutoff.lower[9] ~ 4,
      sd_monthly_PCE < cutoff.lower[10] ~ 4.5,
      sd_monthly_PCE < cutoff.higher[11] ~ 5,
      sd_monthly_PCE < cutoff.higher[2] ~ 5.5,
      sd_monthly_PCE < cutoff.higher[3] ~ 6,
      sd_monthly_PCE < cutoff.higher[4] ~ 6.5,
      sd_monthly_PCE < cutoff.higher[5] ~ 7,
      sd_monthly_PCE < cutoff.higher[6] ~ 7.5,
      sd_monthly_PCE < cutoff.higher[7] ~ 8,
      sd_monthly_PCE < cutoff.higher[8] ~ 8.5,
      sd_monthly_PCE < cutoff.higher[9] ~ 9,
      sd_monthly_PCE < cutoff.higher[10] ~ 9.5,
      sd_monthly_PCE >= cutoff.higher[10] ~ 10,
    ) 
  ) %>% 
  select(communityID, year, urban_score_div)
```

## Data Imputation
```{r}
urban.score.div <- urban.score.div %>%
  left_join(select(psu, communityID, city_eng))

# Proxying missing data with county average
# Find communities with missing data
missing.id <- urban.score.div %>% 
  filter(is.na(urban_score_div)) %>% 
  pull(communityID)

# Computing the county average
county.avg <- urban.score.div %>% 
  group_by(city_eng) %>%
  summarise(score = mean(urban_score_div, na.rm = TRUE))

# Imputation
for(i in 1:length(missing.id)){
  city <- urban.score.div %>% 
    filter(communityID == missing.id[i]) %>% 
    pull(city_eng)
  
  proxy.score <- county.avg %>% 
    filter(city_eng == city) %>% 
    pull(score)
  
  urban.score.div[urban.score.div$communityID == missing.id[i], "urban_score_div"] <- proxy.score
}

# Checking for remaining NA
summary(urban.score.div$urban_score_div)
```

```{r}
ggplot(urban.score.div, aes(x=urban_score_div)) + 
  geom_density(aes(fill=year), alpha=0.7, adjust=2) + 
  scale_x_continuous(breaks = seq(0,10,1), limits=c(0,10)) +
  labs(
    subtitle = "Diversity",
    x = "Score",
    y = "Density",
    fill = "Year"
  ) + 
  theme_light()
```
```{r}
write_csv(urban.score.div, "../../Scores/Individual/diversity.csv")
```

