---
title: "Economic"
author: "Shozen Dan"
date: "9/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=F}
library(tidyverse)
library(haven)
```

```{r}
work.2011 <- read_dta("../../data/Work_Retirement_and_Pension_2011.dta")
work.2013 <- read_dta("../../data/Work_Retirement_and_Pension_2013.dta")
work.2015 <- read_dta("../../data/Work_Retirement_and_Pension_2015.dta")
work.2018 <- read_dta("../../data/Work_Retirement_and_Pension_2018.dta")
```

```{r}
income.2011 <- read_dta("../../data/Household_Income_2011.dta")
income.2013 <- read_dta("../../data/Household_Income_2013.dta")
income.2015 <- read_dta("../../data/Household_Income_2015.dta")
income.2018 <- read_dta("../../data/Household_Income_2018.dta")
```

```{r}
psu <- read_dta("../../data/PSU.dta") %>% 
  dplyr::select(communityID,province_eng, city_eng, urban_nbs)
```

## Construction
```{r, message=FALSE}
exp.2011 <- income.2011 %>% 
  select(communityID, ge004, ge006, ge007, ge009_1, ge009_5, ge009_7) %>% 
  mutate(
    ge004 = ifelse(ge004 == 0, 1, ge004),
    ge006 = replace_na(ge006, 0),
    ge007 = replace_na(ge007, 0),
    food_expence = 4*(ge006 + ge007)/ge004,
    ge009_1 = case_when(
      ge009_1 < 0 ~ 0,
      TRUE ~ ge009_1
    ),
    ge009_5 = case_when(
      ge009_5 < 0 ~ 0,
      TRUE ~ ge009_5
    ),
    ge009_7 = case_when(
      ge009_7 < 0 ~ 0,
      TRUE ~ ge009_7
    )
  ) %>%
  filter(food_expence != Inf | food_expence != -Inf) %>% 
  group_by(communityID) %>% 
  summarise(
    food = mean(food_expence, na.rm = T),
    comm = mean(ge009_1, na.rm = T),
    trans = mean(ge009_5, na.rm = T),
    ent = mean(ge009_7, na.rm = T)
  ) %>% 
  mutate(urban_score_exp = log(food + comm + trans + ent)) %>% 
  select(communityID, urban_score_exp)

exp.2013 <- income.2013 %>% 
  select(communityID, ge004, ge006, ge007, ge009_1, ge009_5, ge009_7) %>% 
  mutate(
    ge004 = ifelse(ge004 == 0, 1, ge004),
    ge006 = replace_na(ge006, 0),
    ge007 = replace_na(ge007, 0),
    food_expence = 4*(ge006 + ge007)/ge004,
    ge009_1 = case_when(
      ge009_1 < 0 ~ 0,
      TRUE ~ ge009_1
    ),
    ge009_5 = case_when(
      ge009_5 < 0 ~ 0,
      TRUE ~ ge009_5
    ),
    ge009_7 = case_when(
      ge009_7 < 0 ~ 0,
      TRUE ~ ge009_7
    )
  ) %>%
  filter(food_expence != Inf | food_expence != -Inf) %>% 
  group_by(communityID) %>% 
  summarise(
    food = mean(food_expence, na.rm = T),
    comm = mean(ge009_1, na.rm = T),
    trans = mean(ge009_5, na.rm = T),
    ent = mean(ge009_7, na.rm = T)
  ) %>% 
  mutate(urban_score_exp = log(food + comm + trans + ent)) %>% 
  select(communityID, urban_score_exp)

exp.2015 <- income.2015 %>% 
  select(communityID, ge004, ge006, ge007, ge009_1, ge009_5, ge009_7) %>% 
  mutate(
    ge004 = ifelse(ge004 == 0, 1, ge004),
    ge006 = replace_na(ge006, 0),
    ge007 = replace_na(ge007, 0),
    food_expence = 4*(ge006 + ge007)/ge004,
    ge009_1 = case_when(
      ge009_1 < 0 ~ 0,
      TRUE ~ ge009_1
    ),
    ge009_5 = case_when(
      ge009_5 < 0 ~ 0,
      TRUE ~ ge009_5
    ),
    ge009_7 = case_when(
      ge009_7 < 0 ~ 0,
      TRUE ~ ge009_7
    )
  ) %>%
  filter(food_expence != Inf | food_expence != -Inf) %>% 
  group_by(communityID) %>% 
  summarise(
    food = mean(food_expence, na.rm = T),
    comm = mean(ge009_1, na.rm = T),
    trans = mean(ge009_5, na.rm = T),
    ent = mean(ge009_7, na.rm = T)
  ) %>% 
  mutate(urban_score_exp = log(food + comm + trans + ent + 2.14)) %>% 
  select(communityID, urban_score_exp)

exp.2018 <- income.2018 %>% 
  select(communityID, ge004, ge006_w4, ge007_w4, ge009_1, ge009_5, ge009_7) %>% 
  mutate(
    ge004 = ifelse(ge004 == 0, 1, ge004),
    ge006_w4 = replace_na(ge006_w4, 0),
    ge007_w4 = replace_na(ge007_w4, 0),
    food_expence = 4*(ge006_w4 + ge007_w4)/ge004,
    ge009_1 = case_when(
      ge009_1 < 0 ~ 0,
      TRUE ~ ge009_1
    ),
    ge009_5 = case_when(
      ge009_5 < 0 ~ 0,
      TRUE ~ ge009_5
    ),
    ge009_7 = case_when(
      ge009_7 < 0 ~ 0,
      TRUE ~ ge009_7
    )
  ) %>%
  filter(food_expence != Inf | food_expence != -Inf) %>% 
  group_by(communityID) %>% 
  summarise(
    food = mean(food_expence, na.rm = T),
    comm = mean(ge009_1, na.rm = T),
    trans = mean(ge009_5, na.rm = T),
    ent = mean(ge009_7, na.rm = T)
  ) %>% 
  mutate(urban_score_exp = log(food + comm + trans + ent)) %>% 
  select(communityID, urban_score_exp)
```

## Imputation
```{r}
summary(exp.2011$urban_score_exp)
summary(exp.2013$urban_score_exp)
summary(exp.2015$urban_score_exp)
summary(exp.2018$urban_score_exp)
```

```{r}
temp.exp <- rbind(
  mutate(exp.2011, year=2011),
  mutate(exp.2013, year=2013),
  mutate(exp.2015, year=2015),
  mutate(exp.2018, year=2018)
)

ggplot(temp.exp, aes(x=urban_score_exp, color=year)) + 
  geom_density(size=0.7) + 
  #ylim(c(0,2)) +
  theme_minimal() + 
  scale_color_manual(values = c("#003f5c", "#7a5195", "#ef5675", "#ffa600")) +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  )

outlier <- quantile(temp.exp$urban_score_exp, probs = c(.05, .95))

median.score <- median(temp.exp$urban_score_exp)
min.score <- min(temp.exp$urban_score_exp)
max.score <- max(temp.exp$urban_score_exp)

seq(from=outlier[1], to=median.score, length.out = 11)
seq(from=median.score, to=outlier[2], length.out = 10)

temp.exp <- temp.exp %>%
  mutate(
    urban_score_exp = case_when(
      urban_score_exp < 5.352640 ~ 0,
      urban_score_exp < 5.432334 ~ 0.5,
      urban_score_exp < 5.512028 ~ 1,
      urban_score_exp < 5.591721 ~ 1.5,
      urban_score_exp < 5.671415 ~ 2,
      urban_score_exp < 5.751108 ~ 2.5,
      urban_score_exp < 5.830802 ~ 3,
      urban_score_exp < 5.910496 ~ 3.5,
      urban_score_exp < 5.990189 ~ 4,
      urban_score_exp < 6.069883 ~ 4.5,
      urban_score_exp < 6.149577 ~ 5,
      urban_score_exp < 6.264961 ~ 5.5,
      urban_score_exp < 6.380345 ~ 6,
      urban_score_exp < 6.495728 ~ 6.5,
      urban_score_exp < 6.611112 ~ 7,
      urban_score_exp < 6.726496 ~ 7.5,
      urban_score_exp < 6.841880 ~ 8,
      urban_score_exp < 6.957264 ~ 8.5,
      urban_score_exp < 7.072648 ~ 9,
      urban_score_exp < 7.188032 ~ 9.5,
      urban_score_exp >= 7.188032 ~ 10
    )
  )
```

```{r}
ggplot(temp.exp, aes(x=urban_score_exp, color=factor(year))) + 
  geom_density(size=0.7) + 
  ylim(c(0,0.3)) +
  scale_x_continuous(breaks = seq(0,10,1), limits=c(0,10)) +
  scale_color_manual(values = c("#003f5c", "#7a5195", "#ef5675", "#ffa600")) +
  theme_minimal() + 
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  )
```


```{r, message=FALSE}
work.2011$fa001

econ.2011 <- work.2011 %>% 
  select(communityID, fa001) %>% 
  mutate(agri_work = ifelse(fa001 == 1, 1, 0)) %>% 
  group_by(communityID) %>% 
  summarise(agri_work = mean(agri_work, na.rm=T)) %>% 
  mutate(urban_score_econ = 10*(1 - agri_work))

econ.2013 <- work.2013 %>% 
  select(communityID, fa001) %>% 
  mutate(agri_work = ifelse(fa001 == 1, 1, 0)) %>% 
  group_by(communityID) %>% 
  summarise(agri_work = mean(agri_work, na.rm=T)) %>% 
  mutate(urban_score_econ = 10*(1 - agri_work))

econ.2015 <- work.2015 %>% 
  select(communityID, fa001) %>% 
  mutate(agri_work = ifelse(fa001 == 1, 1, 0)) %>% 
  group_by(communityID) %>% 
  summarise(agri_work = mean(agri_work, na.rm=T)) %>% 
  mutate(urban_score_econ = 10*(1 - agri_work))

econ.2018 <- work.2018 %>% 
  select(communityID, fc008) %>% 
  mutate(agri_work = ifelse(fc008 == 1, 1, 0)) %>% 
  group_by(communityID) %>% 
  summarise(agri_work = mean(agri_work, na.rm=T)) %>% 
  mutate(urban_score_econ = 10*(1 - agri_work))
```

## Imputation
```{r}
summary(econ.2011$urban_score_econ)
summary(econ.2013$urban_score_econ)
summary(econ.2015$urban_score_econ)
summary(econ.2018$urban_score_econ)
```

```{r}
temp.econ <- rbind(
  mutate(econ.2011, year=2011),
  mutate(econ.2013, year=2013),
  mutate(econ.2015, year=2015),
  mutate(econ.2018, year=2018)
)

ggplot(temp.econ, aes(x=urban_score_econ, color=factor(year))) + 
  geom_density(size=0.7) + 
  ylim(c(0,0.35)) +
  theme_minimal() + 
  scale_color_manual(values = c("#003f5c", "#7a5195", "#ef5675", "#ffa600")) +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  )
```

```{r}
urban.score.econ <- left_join(temp.econ, temp.exp, by=c("communityID", "year")) %>% 
  mutate(urban_score_econ = (urban_score_econ + urban_score_exp)/2) %>% 
  select(communityID, urban_score_econ, year)

ggplot(urban.score.econ, aes(x=urban_score_econ, color=factor(year))) + 
  geom_density(size=0.7) + 
  scale_x_continuous(breaks = seq(0,10,1), limits=c(0,10)) +
  labs(
    x = "Score",
    y = "Density"
  ) + 
  ylim(c(0,0.35)) +
  theme_minimal() + 
  scale_color_manual(values = c("#003f5c", "#7a5195", "#ef5675", "#ffa600")) +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  )
```
```{r}
write_csv(urban.score.econ, "../../Scores/Individual/economic.csv")
```

