---
title: "Healthcare Insurance"
author: "Shozen Dan"
date: "10/14/2020"
output: html_document
---

```{r}
library(tidyverse)
library(haven)
```

```{r}
health.2011 <- read_dta("~/Downloads/Stanford CARE SRI/data/diabetes/data/CHARLS/Health_Care_and_Insurance_2011.dta")
health.2013 <- read_dta("~/Downloads/Stanford CARE SRI/data/diabetes/data/CHARLS/Health_Care_and_Insurance_2013.dta")
health.2015 <- read_dta("~/Downloads/Stanford CARE SRI/data/diabetes/data/CHARLS/Health_Care_and_Insurance_2015.dta")
health.2018 <- read_dta("~/Downloads/Stanford CARE SRI/data/diabetes/data/CHARLS/Health_Care_and_Insurance_2018.dta")
```

```{r}
insr.2011 <- health.2011 %>% 
  select(communityID, starts_with("ea001")) %>% 
  replace(is.na(.), 0)

insr.2011 <- insr.2011 %>% 
  group_by(communityID) %>% 
  summarise(
    ea001s1 = mean(ea001s1),
    ea001s2 = mean(ea001s2)/2,
    ea001s3 = mean(ea001s3)/3,
    ea001s4 = mean(ea001s4)/4,
    ea001s5 = mean(ea001s5)/5
  ) %>% 
  mutate(
    urban_score_insr = 10*(2*ea001s1 + 2*ea001s2 + 1*ea001s3 + 1.5*ea001s4)/2,
    year = "2011"
  ) %>% 
  select(communityID, year, urban_score_insr)

insr.2013 <- health.2013 %>% 
  select(communityID, starts_with("ea001")) %>% 
  replace(is.na(.), 0)

insr.2013 <- insr.2013 %>% 
  group_by(communityID) %>% 
  summarise(
    ea001s1 = mean(ea001s1),
    ea001s2 = mean(ea001s2)/2,
    ea001s3 = mean(ea001s3)/3,
    ea001s4 = mean(ea001s4)/4,
    ea001s5 = mean(ea001s5)/5
  ) %>% 
  mutate(
    urban_score_insr = 10*(2*ea001s1 + 2*ea001s2 + 1*ea001s3 + 1.5*ea001s4)/2,
    year = "2013"
  ) %>% 
  select(communityID, year, urban_score_insr)


insr.2015 <- health.2015 %>% 
  select(communityID, starts_with("ea001_w3_")) %>%
  replace(is.na(.),2) %>%
  mutate(
    ea001s1 = ifelse(ea001_w3_2_1_ == 1 | ea001_w3_3_1_ == 1, 1, 0),
    ea001s2 = ifelse(ea001_w3_2_2_ == 1 | ea001_w3_3_2_ == 1, 1, 0),
    ea001s3 = ifelse(ea001_w3_2_3_ == 1 | ea001_w3_3_3_ == 1, 1, 0),
    ea001s4 = ifelse(ea001_w3_2_4_ == 1 | ea001_w3_3_4_ == 1, 1, 0),
    ea001s9 = ifelse(ea001_w3_2_9_ == 1 | ea001_w3_3_9_ == 1, 1, 0),
  ) %>%
  group_by(communityID) %>%
  summarise(
    ea001s1 = mean(ea001s1, na.rm = T),
    ea001s2 = mean(ea001s2, na.rm = T),
    ea001s3 = mean(ea001s3, na.rm = T),
    ea001s4 = mean(ea001s4, na.rm = T),
    ea001s9 = mean(ea001s9, na.rm = T),
  ) %>% 
  mutate(
    urban_score_insr = 10*(2*ea001s1 + 2*ea001s2 + 1*ea001s3 + 1.5*ea001s4 + 2*ea001s9)/2,
    year = "2015"
  ) %>% 
  select(communityID, year, urban_score_insr)

insr.2018 <- insr.2018 <- health.2018 %>% 
  select(communityID, starts_with("ea001_w4_")) %>%
  group_by(communityID) %>%
  summarise(
    ea001s1 = mean(ea001_w4_s1, na.rm = T),
    ea001s2 = mean(ea001_w4_s2, na.rm = T)/2,
    ea001s3 = mean(ea001_w4_s3, na.rm = T)/3,
    ea001s4 = mean(ea001_w4_s4, na.rm = T)/4,
    ea001s9 = mean(ea001_w4_s9, na.rm = T)/9,
  ) %>% 
  mutate(
    urban_score_insr = 10*(2*ea001s1 + 1.5*ea001s2 + 2*ea001s3 + 1*ea001s4 + 2*ea001s9)/2,
    year = "2018"
  ) %>% 
  select(communityID, year, urban_score_insr)
```
```{r}
mean(insr.2011$urban_score_insr)
mean(insr.2013$urban_score_insr)
mean(insr.2015$urban_score_insr)
mean(insr.2018$urban_score_insr)
```

```{r}
urban.score.insr<- rbind(
  mutate(insr.2011),
  mutate(insr.2013),
  mutate(insr.2015),
  mutate(insr.2018)
)

ggplot(urban.score.insr, aes(x = urban_score_insr)) + 
  geom_density(aes(fill = year), alpha=0.7) + 
  scale_x_continuous(breaks = seq(0,10,1)) +
  labs(
    title = "CHARLS Urbanicity Index",
    subtitle = "Health Insurance",
    x = "Score",
    y = "Density"
  ) + 
  theme_light()
```

```{r}
write_csv(urban.score.insr, "score/insurance.csv")
```

