---
title: "Sanitation"
author: "Shozen Dan"
date: "10/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
```

```{r}
house.2011 <- read_dta("../../data/Housing_Characteristics_2011.dta")
house.2013 <- read_dta("../../data/Housing_Characteristics_2013.dta")
house.2015 <- read_dta("../../data/Housing_Characteristics_2015.dta")
house.2018 <- read_dta("../../data/Housing_Characteristics_2018.dta")
```

```{r, message=FALSE}
sani.2011 <- house.2011 %>% 
  select(communityID, i012_3, i014s2, i015) %>%
  mutate(
    i014s2 = replace_na(i014s2, 1),
    indoor_flushable_toilet = ifelse((i012_3 == 1 & i015 == 1) | i014s2 == 2, 1, 0),
    indoor_unflushable_toilet = ifelse(i012_3 == 1 & i015 == 2, 1, 0)
  ) %>% 
  group_by(communityID) %>%
  summarise(
    prop_indoor_flushable_toilet = mean(indoor_flushable_toilet, na.rm = T),
    prop_indoor_unflushable_toilet = mean(indoor_unflushable_toilet, na.rm = T)
  ) %>% 
  mutate(
    urban_score_sani = 10*(2*prop_indoor_flushable_toilet + prop_indoor_unflushable_toilet)/3
  ) %>% 
  select(communityID, urban_score_sani)

sani.2013 <- house.2013 %>% 
  select(communityID, i012_3, i014s2, i015) %>%
  mutate(
    i014s2 = replace_na(i014s2, 1),
    indoor_flushable_toilet = ifelse((i012_3 == 1 & i015 == 1) | i014s2 == 2, 1, 0),
    indoor_unflushable_toilet = ifelse(i012_3 == 1 & i015 == 2, 1, 0)
  ) %>% 
  group_by(communityID) %>%
  summarise(
    prop_indoor_flushable_toilet = mean(indoor_flushable_toilet, na.rm = T),
    prop_indoor_unflushable_toilet = mean(indoor_unflushable_toilet, na.rm = T)
  ) %>% 
  mutate(
    urban_score_sani = 10*(2*prop_indoor_flushable_toilet + prop_indoor_unflushable_toilet)/3
  ) %>% 
  select(communityID, urban_score_sani)

sani.2015 <- house.2015 %>% 
  select(communityID, i012_3, i014s2, i015) %>%
  mutate(
    i014s2 = replace_na(i014s2, 1),
    indoor_flushable_toilet = ifelse((i012_3 == 1 & i015 == 1) | i014s2 == 2, 1, 0),
    indoor_unflushable_toilet = ifelse(i012_3 == 1 & i015 == 2, 1, 0)
  ) %>% 
  group_by(communityID) %>%
  summarise(
    prop_indoor_flushable_toilet = mean(indoor_flushable_toilet, na.rm = T),
    prop_indoor_unflushable_toilet = mean(indoor_unflushable_toilet, na.rm = T)
  ) %>% 
  mutate(
    urban_score_sani = 10*(2*prop_indoor_flushable_toilet + prop_indoor_unflushable_toilet)/3
  ) %>% 
  select(communityID, urban_score_sani)

sani.2018 <- house.2018 %>% 
  select(communityID, i012_3, i014, i015) %>%
  mutate(
    indoor_flushable_toilet = ifelse((i012_3 == 1 & i015 == 1) | i014 == 2 , 1, 0),
    indoor_unflushable_toilet = ifelse(i012_3 == 1 & i015 == 2, 1, 0)
  ) %>% 
  group_by(communityID) %>%
  summarise(
    prop_indoor_flushable_toilet = mean(indoor_flushable_toilet, na.rm = T),
    prop_indoor_unflushable_toilet = mean(indoor_unflushable_toilet, na.rm = T)
  ) %>% 
  mutate(
    urban_score_sani = 10*(2*prop_indoor_flushable_toilet + prop_indoor_unflushable_toilet)/3
  ) %>% 
  select(communityID, urban_score_sani)
```

## Imputation
```{r}
summary(sani.2011$urban_score_sani)
summary(sani.2013$urban_score_sani)
summary(sani.2015$urban_score_sani)
summary(sani.2018$urban_score_sani)

# Impute 2015
sani.na.communityID <- sani.2015 %>% filter(is.na(urban_score_sani)) %>% pull(communityID)
sani.score.proxy <- sani.2015 %>% left_join(psu, by="communityID") %>% group_by(city_eng) %>% summarise(score = mean(urban_score_sani, na.rm = T))
for(i in 1:length(sani.na.communityID)){
  city <- sani.2015 %>% 
    left_join(psu, by="communityID") %>% 
    filter(communityID == sani.na.communityID[i]) %>% 
    pull(city_eng)
  
  score <- sani.score.proxy %>% 
    filter(city_eng == city) %>% 
    pull(score)
  
  sani.2015[sani.2015$communityID == sani.na.communityID[i], "urban_score_sani"] <- score
}
summary(sani.2015$urban_score_sani)

# Impute 2018
sani.na.communityID <- sani.2018 %>% filter(is.na(urban_score_sani)) %>% pull(communityID)
sani.score.proxy <- sani.2018 %>% left_join(psu, by="communityID") %>% group_by(city_eng) %>% summarise(score = mean(urban_score_sani, na.rm = T))
for(i in 1:length(sani.na.communityID)){
  city <- sani.2018 %>% 
    left_join(psu, by="communityID") %>% 
    filter(communityID == sani.na.communityID[i]) %>% 
    pull(city_eng)
  
  score <- sani.score.proxy %>% 
    filter(city_eng == city) %>% 
    pull(score)
  
  sani.2018[sani.2018$communityID == sani.na.communityID[i], "urban_score_sani"] <- score
}
summary(sani.2018$urban_score_sani)

sani.2018[is.na(sani.2018$urban_score_sani), "urban_score_sani"] <- sani.2015 %>% 
  left_join(psu, by="communityID") %>% 
  filter(city_eng == "Jiamusi") %>% 
  pull(urban_score_sani)

summary(sani.2018$urban_score_sani)
```


```{r}
urban.score.sani <- rbind(
  mutate(sani.2011, year="2011"),
  mutate(sani.2013, year="2013"),
  mutate(sani.2015, year="2015"),
  mutate(sani.2018, year="2018")
)

ggplot(urban.score.sani, aes(x = urban_score_sani)) + 
  geom_density(aes(fill = year), alpha=0.7) + 
  scale_x_continuous(breaks = seq(0,10,1)) +
  labs(
    title = "CHARLS Urbanicity Index",
    subtitle = "Sanitation",
    x = "Score",
    y = "Density"
  ) + 
  theme_light()
```
```{r}
write_csv(urban.score.sani, "../../Scores/Individual/sanitation.csv")
```

