---
title: "Internal Validation"
author: "Shozen Dan"
date: "10/3/2020"
output: html_document
---

```{r, message=FALSE}
library(tidyverse)
library(haven)
```

```{r, message=FALSE}
# read files
comm <- read_csv("score/communication.csv")
house <- read_csv("score/housing.csv")
econ <- read_csv("score/economic.csv")
sani <- read_csv("score/sanitation.csv")
insr <- read_csv("score/insurance.csv")
# div <- read_csv("score/diversity.csv")
psu <- read_dta("~/Downloads/Stanford CARE SRI/data/diabetes/data/CHARLS/PSU.dta") %>% dplyr::select(communityID, province_eng, city_eng, urban_nbs)

# join data frames
urban.score <- comm %>% 
  left_join(house, by=c("communityID","year")) %>% 
  left_join(econ, by=c("communityID","year")) %>% 
  left_join(sani, by=c("communityID","year")) %>% 
  left_join(insr, by=c("communityID","year")) %>% 
  # left_join(div, by=c("communityID","year")) %>% 
  left_join(psu, by="communityID") %>% 
  mutate(urban_score = urban_score_comm + urban_score_house + urban_score_econ + urban_score_sani + urban_score_insr)

urban.score$year <- as.factor(urban.score$year)
urban.score$urban_flag <- as.factor(urban.score$urban_nbs)

write_csv(urban.score, "score/urbanicity.csv")
```

```{r}
ggplot(urban.score, aes(x = urban_score)) + 
  geom_density(aes(fill=year), alpha=0.7) + 
  scale_x_continuous(breaks = seq(0,40,5)) +
  labs(
    title = "CHARLS Urbanicity Index",
    subtitle = "Urbanicity",
    x = "Score",
    y = "Density"
  ) + 
  theme_light()
```

```{r}
urban.score.2011 <- urban.score %>% 
  filter(year == "2011") %>%
  dplyr::select(
    urban_score_comm,
    urban_score_house,
    urban_score_econ,
    #urban_score_div,
    urban_score_sani,
    urban_score_insr
  )

urban.score.2013 <- urban.score %>% 
  filter(year == "2013") %>%
  dplyr::select( 
    urban_score_comm,
    urban_score_house,
    urban_score_econ,
    #urban_score_div,
    urban_score_sani,
    urban_score_insr
  )

urban.score.2015 <- urban.score %>% 
  filter(year == "2015") %>%
  dplyr::select(
    urban_score_comm,
    urban_score_house,
    urban_score_econ,
    #urban_score_div,
    urban_score_sani,
    urban_score_insr
  )
  
urban.score.2018 <- urban.score %>% 
  filter(year == "2018") %>%
  dplyr::select(
    urban_score_comm,
    urban_score_house,
    urban_score_econ,
    #urban_score_div,
    urban_score_sani,
    urban_score_insr
  )

ltm::cronbach.alpha(urban.score.2011, na.rm=TRUE)
ltm::cronbach.alpha(urban.score.2013, na.rm=TRUE)
ltm::cronbach.alpha(urban.score.2015, na.rm=TRUE)
ltm::cronbach.alpha(urban.score.2018, na.rm=TRUE)
```
```{r}
multilevel::item.total(urban.score.2011)
multilevel::item.total(urban.score.2013)
multilevel::item.total(urban.score.2015)
multilevel::item.total(urban.score.2018)
```

```{r}
library(nFactors)
urban.score.clean <- urban.score %>% 
  dplyr::select(urban_score_comm, urban_score_house, urban_score_sani, urban_score_econ, urban_score_insr) %>% 
  drop_na()
factanal(urban.score.clean, 1, rotation = "varimax")
ev <- eigen(cor(urban.score.2011)) # get eigenvalues
ap <- parallel(subject = nrow(urban.score.2011), var = ncol(urban.score.2011), rep = 100, cent = .05)
nS <- nScree(x=ev$values, aparallel = ap$eigen$qevpea)
plotnScree(nS)
```

```{r}
library(FactoMineR)
result <- PCA(urban.score.clean)
```


