---
title: "Construct Valididty"
author: "Shozen Dan"
date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(haven)
```

```{r import data, message=FALSE}
demo.2011 <- read_dta("../../data/Demographic_Background_2011.dta")
demo.2015 <- read_dta("../../data/Demographic_Background_2015.dta")
bio.2011 <- read_dta("../../data/Biomarker_2011.dta")
bio.2015 <- read_dta("../../data/Biomarker_2015.dta")
urban.score <- read_csv("../../Scores/Individual/urbanicity.csv")
psu <- read_dta("../../data/PSU.dta")
```

## 1. Exploratory Analysis of Urbanicity Score
### 1.1 Baseline Urbanicity Scores
```{r}
urb.baseline <- urban.score %>% filter(year == 2011)

ggplot(urb.baseline, aes(x = urban_score)) +
  geom_histogram(aes(y = ..density..), bins = 40, color = "grey30") + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(0, 40, 5)) + 
  labs(x = "Urban Score", y = "Density") + 
  theme_light()
```

### Divide Scores in to Quintiles
```{r}
urb.quintile <- quantile(urb.baseline$urban_score, seq(0, 1, .2))

urb.baseline <- urb.baseline %>% 
  mutate(
    quintile = case_when(
      urban_score < urb.quintile[2] ~ 1,
      urban_score < urb.quintile[3] ~ 2,
      urban_score < urb.quintile[4] ~ 3,
      urban_score < urb.quintile[5] ~ 4,
      urban_score < urb.quintile[6] ~ 5
    )
  )
```

### 1.2 2015 Urbanicity Scores
```{r}
urb.2015 <- urban.score %>% filter(year == 2015)

ggplot(urb.2015, aes(x = urban_score)) +
  geom_histogram(aes(y = ..density..), bins = 40, color = "grey30") + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(0, 40, 5)) + 
  labs(x = "Urban Score", y = "Density") + 
  theme_light()
```

### Change in Urbanicity
```{r}
urb.change <- urban.score %>% 
  select(communityID, year, urban_score) %>%
  filter(year == 2011 | year == 2015) %>% 
  pivot_wider(
    id_cols = communityID, 
    names_from = year, 
    names_prefix = "urban_score_", 
    values_from = urban_score
  ) %>% 
  mutate(urban_score_change = urban_score_2015 - urban_score_2011) %>% 
  drop_na()

ggplot(urb.change, aes(x = urban_score_change)) + 
  geom_histogram(aes(y = ..density..), bins = 30, color = "grey30") +
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  labs(x = "Change in urbanicity score", y = "Density") + 
  theme_light()
```

```{r}
urb.change.quantile <- quantile(urb.change$urban_score_change, probs = seq(0, 1, .25))

urb.quintile <- quantile(urb.baseline$urban_score, seq(0, 1, .2))
urb.change.quintile <- quantile(urb.change$urban_score_change, probs = seq(0, 1, .2))

urb.change <- urb.change %>%
  mutate(
    baseline_quintile = case_when(
      urban_score_2011 < urb.quintile[2] ~ 1,
      urban_score_2011 < urb.quintile[3] ~ 2,
      urban_score_2011 < urb.quintile[4] ~ 3,
      urban_score_2011 < urb.quintile[5] ~ 4,
      urban_score_2011 < urb.quintile[6] ~ 5
    ),
    quantile = case_when(
      urban_score_change < urb.change.quantile[2] ~ 1,
      urban_score_change < urb.change.quantile[3] ~ 2,
      urban_score_change < urb.change.quantile[4] ~ 3,
      urban_score_change < urb.change.quantile[5] ~ 4,
    ),
    quintile = case_when(
      urban_score_change < urb.change.quintile[2] ~ 1,
      urban_score_change < urb.change.quintile[3] ~ 2,
      urban_score_change < urb.change.quintile[4] ~ 3,
      urban_score_change < urb.change.quintile[5] ~ 4,
      urban_score_change < urb.change.quintile[6] ~ 5
    )
  ) %>% 
  drop_na()

urb.change$baseline_quintile <- factor(urb.change$baseline_quintile)

ggplot(urb.change, aes(x = urban_score_2011, y = urban_score_change)) + 
  geom_point() + 
  geom_smooth() +
  labs(x = "Baseline Urbanicity", y = "Change in Urbanicity") +
  theme_light()
```
```{r}
tmp <- urb.scores %>% 
  filter(year == 2011 | year == 2018) %>% 
  select(communityID, year, urban_score) %>% 
  pivot_wider(names_from = year, values_from = urban_score, names_prefix = "urban_score_") %>% 
  mutate(urban_score_change = urban_score_2018 - urban_score_2011)

ggplot(tmp, aes(x = urban_score_2011, y = urban_score_change)) + 
  geom_point() + 
  geom_smooth() +
  labs(x = "Baseline Urbanicity", y = "Change in Urbanicity") +
  theme_light()
```


```{r}
cor.test(urb.change$urban_score_2011, urb.change$urban_score_change)
```

```{r}
urb.change <- urb.change %>% 
  mutate(
    category = case_when(
      urban_score_2011 < 10 & urban_score_change <= 5 ~ "B10+5",
      urban_score_2011 < 10 & urban_score_change <= 10 ~ "B10+10",
      
      urban_score_2011 < 20 & urban_score_change <= 5 ~ "B20+5",
      urban_score_2011 < 20 & urban_score_change <= 10 ~ "B20+10",
      
      urban_score_2011 < 30 & urban_score_change <= 5 ~ "B30+5",
      urban_score_2011 < 30 & urban_score_change <= 10 ~ "B30+10",
    )
  )
```


```{r}
# urb.change <- rename(urb.change, change_quintile = quintile)
urb.change$quintile <- factor(urb.change$quintile)
urb.change$quantile <- factor(urb.change$quantile)
urb.change$baseline <- factor(urb.change$baseline)

urb.change
```


### Compute BMI
* `qi002`: height in centimeters
* `ql002`: weight in kg
```{r}
bmi.2011 <- bio.2011 %>% 
  mutate( # Adjusting ID
    householdID = str_c(householdID, "0"),
    ID = str_c(householdID, substring(ID, 10, 11))
  ) %>%
  select(ID, householdID, communityID, qi002, ql002) %>%
  rename(height = qi002, weight = ql002) %>%
  drop_na() %>% 
  filter(height != 999, height != 993) %>% # remove invalid entries
  filter(weight != 999, weight != 993) %>% # remove invalid entries
  mutate(
    bmi = weight/(height/100)^2, # compute bmi
    overweight = ifelse(bmi >= 25, 1, 0), # overweight: bmi >= 25
  )

bmi.2015 <- bio.2015 %>% 
  select(ID, householdID, communityID, qi002, ql002) %>%
  rename(height = qi002, weight = ql002) %>%
  drop_na() %>% 
  filter(height != 999, height != 993) %>% # remove invalid entries
  filter(weight != 999, weight != 993) %>% # remove invalid entries
  mutate(
    bmi = weight/(height/100)^2, # compute bmi
    overweight = ifelse(bmi >= 25, 1, 0), # overweight: bmi >= 25
  )
```

```{r}
sex <- demo.2015 %>% 
  select(ID, ba000_w2_3) %>% 
  rename(sex = ba000_w2_3)
  
age <- demo.2011 %>% 
  mutate( # adujst ID 
    householdID = str_c(householdID, "0"),
    ID = str_c(householdID, substring(ID, 10, 11)),
    age = 2011 - ba002_1,
    ageSQ = age^2
  ) %>%
  select(ID, householdID, communityID, age,ageSQ) %>% 
  drop_na()

# Join data frames
cohort.2011 <- left_join(age, sex, by = "ID") %>% 
  left_join(bmi.2011, by = c("ID", "householdID", "communityID")) %>% 
  filter(overweight == 0) # Females not overweight at baseline
```

### Join Dataframes
```{r}
bmi.2015.subset <- bmi.2015[bmi.2015$ID %in% cohort.2011$ID,]
cohort <- cohort.2011[cohort.2011$ID %in% bmi.2015$ID,]

cohort <- cohort %>%
  select(-overweight) %>%
  left_join(
    select(bmi.2015.subset, ID, overweight), 
    by = "ID"
  ) %>% 
  left_join(
    select(urb.change, communityID, baseline, category),
    by = "communityID"
  )
```

### Fixed Effects Regression
```{r}
cohort <- cohort %>% mutate(sex = ifelse(sex == 1, "Male", "Female"))
cohort$category <- factor(cohort$category, levels = c("B10+5", "B10+10", "B20+5", "B20+10", "B30+5", "B30+10"))
```

```{r}
glm.mod <- glm(overweight ~ age + sex + category, cohort, family = "binomial")
summary(glm.mod)
```

```{r}
cohort <- cohort %>% left_join(psu, by="communityID")

glm.mod2 <- glm(overweight ~ age + sex + urban_nbs, cohort, family = "binomial")
summary(glm.mod2)
```


### Create Forest Plot
```{r}
or <- exp(coef(glm.mod)) # extract and exponentiate coefs
se <- sqrt(diag(vcov(glm.mod))) # extract Var and covert to SE
lower <- exp(coef(glm.mod) - qnorm(0.975) * se) # 95% C.I. lower bound
upper <- exp(coef(glm.mod) + qnorm(0.975) * se) # 95% C.I. higher bound
tmp <- data.frame(cbind(or, lower, upper)) # create data frame
tmp
```
```{r}
clean.names <- c(
  "(Intercept)",
  "Age",
  "Male",
  "Baseline <10\nIncrease <=10",
  "Baseline <20\nIncrease <=5",
  "Baseline <20\nIncrease <=10",
  "Baseline <30\nIncrease <=5",
  "Baseline <30\nIncrease <=10"
)

row.names(tmp) <- clean.names
odds <- tmp[-1, ]

# Creating reference points
ref.sex <- data.frame(row.names = "Female", or = 1, lower = 1, upper = 1)
ref.category <- data.frame(row.names = "Baseline <10\nIncrease <=5", or = 1, lower = 1, upper = 1)

odds
```
```{r}
odds <- rbind(
  odds[1,],
  ref.sex, odds[2,],
  ref.category, odds[4,],
  odds[5:7,]
)
```

```{r}
odds$vars <- row.names(odds) # create a new column called vars

odds <- odds %>% # create a new column called category and sort the variables into the category you want. This is used later to add the colors.
  mutate(
    category = case_when(
      vars == "Age" ~ "Age",
      vars == "Female" ~ "Sex",
      vars == "Male" ~ "Sex",
      TRUE ~ "Urbanicity"
    )
  )

odds$vars <- factor(odds$vars, levels=odds$vars)
odds$category <- factor(odds$category, levels = c("Urbanicity", "Sex",  "Age"))
color.schema <- c("#ffa600", "#bc5090", "#003f5c")
```

```{r}
ggplot(odds, aes(y = or, x = vars, color=category)) + 
  geom_hline(yintercept = 1, linetype = 2) + 
  geom_point(size=6) + 
  geom_errorbar(aes(ymin = lower, ymax = upper), width = .2) + 
  scale_y_log10() + 
  annotate("text", y = odds$or, x = 1:nrow(odds), label = round(odds$or, 2), size=2, color="white") + 
  scale_colour_manual(values = color.schema) + 
  labs(
    x = element_blank(),
    y = "Odds Ratio"
  ) +
  theme_bw() +
  theme(
    axis.text.y = element_text(size = 11),
    legend.position = "none"
  )
```


